blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/ItsRiprod/doctale/discussions
    about: Ask questions or start a discussion about the documentation
